### ISSUE TITLE
default config doesn't build for relevant architecture on Intel Mac

### ISSUE THREAD

**Issue by trevoranderson** [jhugman/uniffi-bindgen-react-native#134]
The default config is

```
---
name: MyRustLib
rust:
  repo: https://github.com/ianthetechie/uniffi-starter
  branch: main
  manifestPath: rust/foobar/Cargo.toml
```

When it builds on iOS it only builds Arm targetes, but on an Intel Mac, the simulator is x86, so it fails to link.
The following config builds on Intel Mac:

```
---
name: MyRustLib
rust:
  repo: https://github.com/ianthetechie/uniffi-starter
  branch: main
  manifestPath: rust/foobar/Cargo.toml
ios:
    directory: ios
    targets:
    - aarch64-apple-ios
    - aarch64-apple-ios-sim
    - x86_64-apple-ios
```
