### ISSUE TITLE
Building two simulator frameworks requires using lipo on the artifacts

### ISSUE THREAD

**Issue by zzorba** [jhugman/uniffi-bindgen-react-native#77]
If you specify both an x86 and an arm64 simulator in your .yaml file:

```
ios:
  directory: ios
  targets:
    - aarch64-apple-ios
    - aarch64-apple-ios-sim
    - x86_64-apple-ios
```

Building on iOS will attempt to create an xcframework, but it will fail because it contains TWO simulator targets.  Based on the code in the matrix-rust-sdk, https://github.com/matrix-org/matrix-rust-sdk/blob/main/xtask/src/swift.rs, the correct thing to do in this situation is to use `lipo` on the two simulator lib files to produce a single fat lib.  This can then be passed successfully to the xcframework command.

I don't know how urgent this is to FIX FIX, given that x86 is on the way out.  But having uniffi bindgen detect both x86 and arm64 simulators and call it out as unsupported seems better.

Adding an option to skip the .xcframework creation would also be a helpful escape hatch.
